-- VPMED KHOA DƯỢC
-- KHÔI PHỤC LƯU SUPABASE CHO CÔNG CỤ SUY THẬN VÀ KHÁNG SINH NHI
--
-- Chạy TOÀN BỘ file này một lần trong Supabase SQL Editor của project đang
-- cấu hình tại assets/js/server-config.js.
-- File chạy lặp lại an toàn, không xóa tài khoản và không xóa lịch sử cũ.

begin;

-- 1. Mở rộng đúng bảng cấp quyền đang được website hiện tại sử dụng.
alter table public.pharmacy_staff_members
  add column if not exists full_name text,
  add column if not exists job_title text,
  add column if not exists department text,
  add column if not exists role text;

update public.pharmacy_staff_members as staff
set full_name = coalesce(
      nullif(trim(staff.full_name), ''),
      nullif(split_part(users.email, '@', 1), ''),
      'Nhân viên Khoa Dược'
    ),
    job_title = coalesce(nullif(trim(staff.job_title), ''), 'Nhân viên Khoa Dược'),
    department = coalesce(nullif(trim(staff.department), ''), 'Khoa Dược'),
    role = case when staff.role = 'admin' then 'admin' else 'staff' end
from auth.users as users
where users.id = staff.user_id;

update public.pharmacy_staff_members
set full_name = coalesce(nullif(trim(full_name), ''), 'Nhân viên Khoa Dược'),
    job_title = coalesce(nullif(trim(job_title), ''), 'Nhân viên Khoa Dược'),
    department = coalesce(nullif(trim(department), ''), 'Khoa Dược'),
    role = case when role = 'admin' then 'admin' else 'staff' end;

alter table public.pharmacy_staff_members
  alter column full_name set default 'Nhân viên Khoa Dược',
  alter column full_name set not null,
  alter column job_title set default 'Nhân viên Khoa Dược',
  alter column job_title set not null,
  alter column department set default 'Khoa Dược',
  alter column department set not null,
  alter column role set default 'staff',
  alter column role set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.pharmacy_staff_members'::regclass
      and conname = 'pharmacy_staff_members_role_check'
  ) then
    alter table public.pharmacy_staff_members
      add constraint pharmacy_staff_members_role_check
      check (role in ('staff', 'admin'));
  end if;
end;
$$;

-- Tài khoản quản trị gốc đã được dự án cấp quyền trong 02_CAP_QUYEN_NHAN_VIEN.sql.
update public.pharmacy_staff_members as staff
set role = 'admin'
from auth.users as users
where users.id = staff.user_id
  and lower(users.email) = lower('khoaduoc@vpmed.vn');

create or replace function public.is_pharmacy_staff_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.pharmacy_staff_members
    where user_id = auth.uid()
      and role = 'admin'
  );
$$;

revoke all on function public.is_pharmacy_staff_admin() from public;
grant execute on function public.is_pharmacy_staff_admin() to authenticated;

-- 2. Tạo bảng lịch sử dùng chung cho cả suy thận và Nhi khoa.
create table if not exists public.renal_lookup_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  patient_code text not null default 'KHONG_CO_MA',
  staff_name text not null default 'Nhân viên Khoa Dược',
  staff_email text not null default 'Chưa cập nhật',
  job_title text not null default 'Nhân viên Khoa Dược',
  department text not null default 'Khoa Dược',
  lookup_type text not null default 'renal_function',
  module_name text not null default 'Tính liều kháng sinh & CrCl/eGFR',
  drug_name text,
  crcl_ml_min numeric(12, 2),
  egfr_ml_min_1_73m2 numeric(12, 2),
  renal_band text,
  result_summary text,
  created_at timestamptz not null default now()
);

-- Bổ sung cột nếu project đã từng có một phiên bản bảng cũ.
alter table public.renal_lookup_logs
  add column if not exists user_id uuid,
  add column if not exists patient_code text,
  add column if not exists staff_name text,
  add column if not exists staff_email text,
  add column if not exists job_title text,
  add column if not exists department text,
  add column if not exists lookup_type text,
  add column if not exists module_name text,
  add column if not exists drug_name text,
  add column if not exists crcl_ml_min numeric(12, 2),
  add column if not exists egfr_ml_min_1_73m2 numeric(12, 2),
  add column if not exists renal_band text,
  add column if not exists result_summary text,
  add column if not exists created_at timestamptz;

update public.renal_lookup_logs as logs
set patient_code = coalesce(nullif(upper(trim(logs.patient_code)), ''), 'KHONG_CO_MA'),
    staff_name = coalesce(nullif(trim(logs.staff_name), ''), nullif(trim(staff.full_name), ''), 'Nhân viên Khoa Dược'),
    staff_email = coalesce(nullif(trim(logs.staff_email), ''), users.email, 'Chưa cập nhật'),
    job_title = coalesce(nullif(trim(logs.job_title), ''), nullif(trim(staff.job_title), ''), 'Nhân viên Khoa Dược'),
    department = coalesce(nullif(trim(logs.department), ''), nullif(trim(staff.department), ''), 'Khoa Dược'),
    lookup_type = coalesce(nullif(trim(logs.lookup_type), ''), 'renal_function'),
    module_name = coalesce(nullif(trim(logs.module_name), ''), 'Tính liều kháng sinh & CrCl/eGFR'),
    created_at = coalesce(logs.created_at, now())
from public.pharmacy_staff_members as staff
left join auth.users as users on users.id = staff.user_id
where staff.user_id = logs.user_id;

update public.renal_lookup_logs
set patient_code = coalesce(nullif(upper(trim(patient_code)), ''), 'KHONG_CO_MA'),
    staff_name = coalesce(nullif(trim(staff_name), ''), 'Nhân viên Khoa Dược'),
    staff_email = coalesce(nullif(trim(staff_email), ''), 'Chưa cập nhật'),
    job_title = coalesce(nullif(trim(job_title), ''), 'Nhân viên Khoa Dược'),
    department = coalesce(nullif(trim(department), ''), 'Khoa Dược'),
    lookup_type = coalesce(nullif(trim(lookup_type), ''), 'renal_function'),
    module_name = coalesce(nullif(trim(module_name), ''), 'Tính liều kháng sinh & CrCl/eGFR'),
    created_at = coalesce(created_at, now());

alter table public.renal_lookup_logs
  alter column patient_code set default 'KHONG_CO_MA',
  alter column patient_code set not null,
  alter column staff_name set default 'Nhân viên Khoa Dược',
  alter column staff_name set not null,
  alter column staff_email set default 'Chưa cập nhật',
  alter column staff_email set not null,
  alter column job_title set default 'Nhân viên Khoa Dược',
  alter column job_title set not null,
  alter column department set default 'Khoa Dược',
  alter column department set not null,
  alter column lookup_type set default 'renal_function',
  alter column lookup_type set not null,
  alter column module_name set default 'Tính liều kháng sinh & CrCl/eGFR',
  alter column module_name set not null,
  alter column created_at set default now(),
  alter column created_at set not null;

do $$
declare
  constraint_name text;
begin
  for constraint_name in
    select c.conname
    from pg_constraint as c
    where c.conrelid = 'public.renal_lookup_logs'::regclass
      and c.contype = 'c'
      and pg_get_constraintdef(c.oid) ilike '%lookup_type%'
  loop
    execute format('alter table public.renal_lookup_logs drop constraint %I', constraint_name);
  end loop;

  alter table public.renal_lookup_logs
    add constraint renal_lookup_logs_lookup_type_check
    check (lookup_type in (
      'renal_function',
      'antibiotic_renal_dose',
      'colistin_renal_dose',
      'pediatric_antibiotic_dose'
    ));
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.renal_lookup_logs'::regclass
      and conname = 'renal_lookup_logs_patient_code_length'
  ) then
    alter table public.renal_lookup_logs
      add constraint renal_lookup_logs_patient_code_length
      check (char_length(trim(patient_code)) between 1 and 30);
  end if;
end;
$$;

create index if not exists renal_lookup_logs_created_at_idx
  on public.renal_lookup_logs (created_at desc);

create index if not exists renal_lookup_logs_module_created_at_idx
  on public.renal_lookup_logs (module_name, created_at desc);

-- 3. Trigger chỉ tin định danh của phiên đăng nhập, không tin dữ liệu client.
create or replace function public.fill_renal_lookup_identity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_staff record;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select
    staff.user_id,
    staff.full_name,
    staff.job_title,
    staff.department,
    users.email
  into current_staff
  from public.pharmacy_staff_members as staff
  join auth.users as users on users.id = staff.user_id
  where staff.user_id = auth.uid();

  if not found then
    raise exception 'Pharmacy staff permission required';
  end if;

  new.user_id := auth.uid();
  new.patient_code := upper(trim(coalesce(nullif(new.patient_code, ''), 'KHONG_CO_MA')));
  if char_length(new.patient_code) < 1 or char_length(new.patient_code) > 30 then
    raise exception 'Mã bệnh nhân phải có từ 1 đến 30 ký tự';
  end if;
  new.staff_name := current_staff.full_name;
  new.staff_email := current_staff.email;
  new.job_title := current_staff.job_title;
  new.department := current_staff.department;
  new.created_at := now();
  return new;
end;
$$;

revoke all on function public.fill_renal_lookup_identity() from public;

drop trigger if exists set_renal_lookup_identity on public.renal_lookup_logs;
create trigger set_renal_lookup_identity
before insert on public.renal_lookup_logs
for each row execute function public.fill_renal_lookup_identity();

-- 4. RLS: nhân viên Khoa Dược đọc/ghi; chỉ admin được xóa.
alter table public.renal_lookup_logs enable row level security;

drop policy if exists "approved users insert own renal lookups" on public.renal_lookup_logs;
drop policy if exists "pharmacy staff insert calculation logs" on public.renal_lookup_logs;
create policy "pharmacy staff insert calculation logs"
on public.renal_lookup_logs
for insert
to authenticated
with check (
  user_id = auth.uid()
  and public.is_pharmacy_staff()
);

drop policy if exists "approved users read shared renal lookup history" on public.renal_lookup_logs;
drop policy if exists "admins read renal lookup audit" on public.renal_lookup_logs;
drop policy if exists "pharmacy staff read calculation logs" on public.renal_lookup_logs;
create policy "pharmacy staff read calculation logs"
on public.renal_lookup_logs
for select
to authenticated
using (public.is_pharmacy_staff());

drop policy if exists "admins delete shared renal lookup history" on public.renal_lookup_logs;
drop policy if exists "pharmacy admins delete calculation logs" on public.renal_lookup_logs;
create policy "pharmacy admins delete calculation logs"
on public.renal_lookup_logs
for delete
to authenticated
using (public.is_pharmacy_staff_admin());

revoke all on table public.renal_lookup_logs from anon, authenticated;
grant select, insert, delete on table public.renal_lookup_logs to authenticated;

do $$
declare
  identity_sequence text;
begin
  identity_sequence := pg_get_serial_sequence('public.renal_lookup_logs', 'id');
  if identity_sequence is not null then
    execute format('grant usage, select on sequence %s to authenticated', identity_sequence);
  end if;
end;
$$;

-- 5. Trả đúng vai trò cho giao diện mà không mở quyền SELECT bảng thành viên.
create or replace function public.get_my_pharmacy_staff_profile()
returns table (
  user_id uuid,
  email text,
  full_name text,
  job_title text,
  department text,
  role text
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    staff.user_id,
    users.email::text,
    staff.full_name,
    staff.job_title,
    staff.department,
    staff.role
  from public.pharmacy_staff_members as staff
  join auth.users as users on users.id = staff.user_id
  where staff.user_id = auth.uid();
$$;

revoke all on function public.get_my_pharmacy_staff_profile() from public;
grant execute on function public.get_my_pharmacy_staff_profile() to authenticated;

notify pgrst, 'reload schema';

commit;

-- Kết quả kiểm tra: phải có 3 policy, 1 trigger và RPC hồ sơ.
select policyname, cmd, roles
from pg_policies
where schemaname = 'public'
  and tablename = 'renal_lookup_logs'
order by cmd, policyname;

select trigger_name
from information_schema.triggers
where event_object_schema = 'public'
  and event_object_table = 'renal_lookup_logs';

