-- BHYT non-pickup module — schema, aggregation and reconciliation.
-- Safe to run over the first version: existing columns/data are preserved.

create table if not exists public.bhyt_nonpickup_cases (
  record_key text primary key,
  dispense_date date not null,
  serial_no text,
  patient_name text not null,
  phone text,
  reason text not null,
  reason_group text not null,
  source_file text,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.bhyt_nonpickup_cases
  add column if not exists visit_code text,
  add column if not exists prescription_no text,
  add column if not exists insurance_code text,
  add column if not exists diagnosis text,
  add column if not exists total_quantity numeric(18,3) not null default 0,
  add column if not exists total_amount numeric(18,2) not null default 0,
  add column if not exists insurance_amount numeric(18,2) not null default 0,
  add column if not exists patient_amount numeric(18,2) not null default 0;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'bhyt_nonpickup_cases_reason_group_check'
      and conrelid = 'public.bhyt_nonpickup_cases'::regclass
  ) then
    alter table public.bhyt_nonpickup_cases add constraint bhyt_nonpickup_cases_reason_group_check
      check (reason_group in (
        'Quên/không lấy', 'Mua ngoài', 'Không biết/chưa rõ',
        'Không liên lạc được', 'Không đi khám/nghỉ', 'Khác'
      ));
  end if;
end $$;

create table if not exists public.bhyt_nonpickup_items (
  id bigint generated by default as identity primary key,
  case_record_key text not null references public.bhyt_nonpickup_cases(record_key) on delete cascade,
  line_no integer not null,
  drug_code text,
  drug_name text not null,
  unit text not null default 'viên',
  quantity numeric(18,3) not null check (quantity >= 0),
  unit_price numeric(18,4) not null default 0 check (unit_price >= 0),
  total_amount numeric(18,2) not null default 0 check (total_amount >= 0),
  insurance_amount numeric(18,2) not null default 0 check (insurance_amount >= 0),
  patient_amount numeric(18,2) not null default 0 check (patient_amount >= 0),
  created_at timestamptz not null default now(),
  unique (case_record_key, line_no)
);

create table if not exists public.bhyt_monthly_inventory (
  id bigint generated by default as identity primary key,
  inventory_month date not null check (inventory_month = date_trunc('month', inventory_month)::date),
  drug_code text not null,
  drug_name text not null,
  unit text not null default 'viên',
  opening_quantity numeric(18,3) not null default 0,
  received_quantity numeric(18,3) not null default 0,
  actual_issued_quantity numeric(18,3) not null default 0,
  book_closing_quantity numeric(18,3) not null default 0,
  physical_closing_quantity numeric(18,3),
  nonpickup_in_issued boolean not null default true,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (inventory_month, drug_code)
);

create index if not exists bhyt_nonpickup_cases_date_idx on public.bhyt_nonpickup_cases (dispense_date);
create index if not exists bhyt_nonpickup_cases_reason_group_idx on public.bhyt_nonpickup_cases (reason_group);
create index if not exists bhyt_nonpickup_items_case_idx on public.bhyt_nonpickup_items (case_record_key);
create index if not exists bhyt_nonpickup_items_drug_idx on public.bhyt_nonpickup_items (drug_code);
create index if not exists bhyt_monthly_inventory_month_idx on public.bhyt_monthly_inventory (inventory_month);

create or replace function public.bhyt_set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists bhyt_nonpickup_cases_set_updated_at on public.bhyt_nonpickup_cases;
create trigger bhyt_nonpickup_cases_set_updated_at
before update on public.bhyt_nonpickup_cases
for each row execute function public.bhyt_set_updated_at();

drop trigger if exists bhyt_inventory_set_updated_at on public.bhyt_monthly_inventory;
create trigger bhyt_inventory_set_updated_at
before update on public.bhyt_monthly_inventory
for each row execute function public.bhyt_set_updated_at();

create or replace function public.bhyt_refresh_case_totals(p_record_key text)
returns void language sql security invoker set search_path = public as $$
  update public.bhyt_nonpickup_cases c
  set total_quantity = x.total_quantity,
      total_amount = x.total_amount,
      insurance_amount = x.insurance_amount,
      patient_amount = x.patient_amount
  from (
    select coalesce(sum(quantity), 0) as total_quantity,
           coalesce(sum(total_amount), 0) as total_amount,
           coalesce(sum(insurance_amount), 0) as insurance_amount,
           coalesce(sum(patient_amount), 0) as patient_amount
    from public.bhyt_nonpickup_items
    where case_record_key = p_record_key
  ) x
  where c.record_key = p_record_key;
$$;

create or replace function public.bhyt_items_refresh_after_insert()
returns trigger language plpgsql security invoker set search_path = public as $$
declare v_key text;
begin
  for v_key in select distinct case_record_key from new_rows loop
    perform public.bhyt_refresh_case_totals(v_key);
  end loop;
  return null;
end;
$$;

create or replace function public.bhyt_items_refresh_after_delete()
returns trigger language plpgsql security invoker set search_path = public as $$
declare v_key text;
begin
  for v_key in select distinct case_record_key from old_rows loop
    perform public.bhyt_refresh_case_totals(v_key);
  end loop;
  return null;
end;
$$;

create or replace function public.bhyt_items_refresh_after_update()
returns trigger language plpgsql security invoker set search_path = public as $$
declare v_key text;
begin
  for v_key in
    select case_record_key from new_rows union select case_record_key from old_rows
  loop
    perform public.bhyt_refresh_case_totals(v_key);
  end loop;
  return null;
end;
$$;

drop trigger if exists bhyt_items_refresh_parent_totals on public.bhyt_nonpickup_items;
drop trigger if exists bhyt_items_refresh_after_insert on public.bhyt_nonpickup_items;
drop trigger if exists bhyt_items_refresh_after_delete on public.bhyt_nonpickup_items;
drop trigger if exists bhyt_items_refresh_after_update on public.bhyt_nonpickup_items;
create trigger bhyt_items_refresh_after_insert after insert on public.bhyt_nonpickup_items
  referencing new table as new_rows for each statement execute function public.bhyt_items_refresh_after_insert();
create trigger bhyt_items_refresh_after_delete after delete on public.bhyt_nonpickup_items
  referencing old table as old_rows for each statement execute function public.bhyt_items_refresh_after_delete();
create trigger bhyt_items_refresh_after_update after update on public.bhyt_nonpickup_items
  referencing new table as new_rows old table as old_rows for each statement execute function public.bhyt_items_refresh_after_update();

create or replace view public.bhyt_daily_nonpickup_summary
with (security_invoker = true) as
select c.dispense_date,
       count(*)::bigint as patient_count,
       coalesce(sum(c.total_quantity), 0)::numeric(18,3) as suspended_quantity,
       coalesce(sum(c.total_amount), 0)::numeric(18,2) as total_amount,
       coalesce(sum(c.insurance_amount), 0)::numeric(18,2) as insurance_amount,
       coalesce(sum(c.patient_amount), 0)::numeric(18,2) as patient_amount
from public.bhyt_nonpickup_cases c
group by c.dispense_date;

create or replace view public.bhyt_monthly_nonpickup_summary
with (security_invoker = true) as
select date_trunc('month', c.dispense_date)::date as report_month,
       count(*)::bigint as patient_count,
       coalesce(sum(c.total_quantity), 0)::numeric(18,3) as suspended_quantity,
       coalesce(sum(c.total_amount), 0)::numeric(18,2) as total_amount,
       coalesce(sum(c.insurance_amount), 0)::numeric(18,2) as insurance_amount,
       coalesce(sum(c.patient_amount), 0)::numeric(18,2) as patient_amount
from public.bhyt_nonpickup_cases c
group by date_trunc('month', c.dispense_date)::date;

create or replace view public.bhyt_monthly_inventory_reconciliation
with (security_invoker = true) as
with suspended as (
  select date_trunc('month', c.dispense_date)::date as inventory_month,
         coalesce(nullif(upper(btrim(i.drug_code)), ''), '[KHONG-MA]') as drug_code,
         max(i.drug_name) as drug_name,
         max(i.unit) as unit,
         sum(i.quantity)::numeric(18,3) as suspended_quantity,
         sum(i.total_amount)::numeric(18,2) as suspended_amount
  from public.bhyt_nonpickup_cases c
  join public.bhyt_nonpickup_items i on i.case_record_key = c.record_key
  group by date_trunc('month', c.dispense_date)::date, coalesce(nullif(upper(btrim(i.drug_code)), ''), '[KHONG-MA]')
)
select coalesce(inv.inventory_month, s.inventory_month) as inventory_month,
       coalesce(upper(btrim(inv.drug_code)), s.drug_code) as drug_code,
       coalesce(inv.drug_name, s.drug_name) as drug_name,
       coalesce(inv.unit, s.unit, 'viên') as unit,
       coalesce(inv.opening_quantity, 0)::numeric(18,3) as opening_quantity,
       coalesce(inv.received_quantity, 0)::numeric(18,3) as received_quantity,
       coalesce(inv.actual_issued_quantity, 0)::numeric(18,3) as actual_issued_quantity,
       coalesce(inv.book_closing_quantity, 0)::numeric(18,3) as book_closing_quantity,
       inv.physical_closing_quantity,
       coalesce(s.suspended_quantity, 0)::numeric(18,3) as suspended_quantity,
       coalesce(s.suspended_amount, 0)::numeric(18,2) as suspended_amount,
       (coalesce(inv.opening_quantity, 0) + coalesce(inv.received_quantity, 0) - coalesce(inv.actual_issued_quantity, 0))::numeric(18,3) as calculated_book_closing,
       (
         coalesce(inv.opening_quantity, 0) + coalesce(inv.received_quantity, 0)
         - coalesce(inv.actual_issued_quantity, 0)
         + case when coalesce(inv.nonpickup_in_issued, true) then coalesce(s.suspended_quantity, 0) else 0 end
       )::numeric(18,3) as calculated_physical_closing,
       (
         coalesce(inv.opening_quantity, 0) + coalesce(inv.received_quantity, 0)
         - coalesce(inv.actual_issued_quantity, 0)
         + case when coalesce(inv.nonpickup_in_issued, true) then coalesce(s.suspended_quantity, 0) else 0 end
         - coalesce(inv.book_closing_quantity, 0) - coalesce(s.suspended_quantity, 0)
       )::numeric(18,3) as book_formula_variance,
       case when inv.physical_closing_quantity is null then null
            else (inv.physical_closing_quantity - inv.book_closing_quantity)::numeric(18,3) end as physical_book_variance,
       case when inv.physical_closing_quantity is null then
              (
                coalesce(inv.opening_quantity, 0) + coalesce(inv.received_quantity, 0)
                - coalesce(inv.actual_issued_quantity, 0)
                + case when coalesce(inv.nonpickup_in_issued, true) then coalesce(s.suspended_quantity, 0) else 0 end
                - coalesce(inv.book_closing_quantity, 0) - coalesce(s.suspended_quantity, 0)
              )::numeric(18,3)
            else (
              inv.physical_closing_quantity
              - (coalesce(inv.opening_quantity, 0) + coalesce(inv.received_quantity, 0)
                 - coalesce(inv.actual_issued_quantity, 0)
                 + case when coalesce(inv.nonpickup_in_issued, true) then coalesce(s.suspended_quantity, 0) else 0 end)
            )::numeric(18,3) end as unexplained_variance,
       coalesce(inv.nonpickup_in_issued, true) as nonpickup_in_issued,
       (inv.id is null) as missing_inventory
from public.bhyt_monthly_inventory inv
full join suspended s
  on s.inventory_month = inv.inventory_month and s.drug_code = upper(btrim(inv.drug_code));

create or replace function public.bhyt_get_dashboard(p_date date default null, p_month date default null)
returns table (
  period_start date, period_end date, patient_count bigint, suspended_quantity numeric,
  total_amount numeric, insurance_amount numeric, patient_amount numeric,
  inventory_alert_count bigint, unexplained_variance numeric
)
language plpgsql stable security invoker set search_path = public as $$
declare
  v_start date;
  v_end date;
  v_inventory_month date;
begin
  if p_month is not null then
    v_start := date_trunc('month', p_month)::date;
    v_end := (v_start + interval '1 month')::date;
  else
    v_start := coalesce(p_date, current_date);
    v_end := v_start + 1;
  end if;
  v_inventory_month := date_trunc('month', v_start)::date;

  return query
  select v_start, v_end, count(c.record_key)::bigint,
         coalesce(sum(c.total_quantity), 0), coalesce(sum(c.total_amount), 0),
         coalesce(sum(c.insurance_amount), 0), coalesce(sum(c.patient_amount), 0),
         (select count(*)::bigint from public.bhyt_monthly_inventory_reconciliation r
           where r.inventory_month = v_inventory_month
             and (r.missing_inventory or abs(r.book_formula_variance) > 0.001
                  or (r.unexplained_variance is not null and abs(r.unexplained_variance) > 0.001))),
         (select coalesce(sum(r.unexplained_variance), 0)
            from public.bhyt_monthly_inventory_reconciliation r where r.inventory_month = v_inventory_month)
  from public.bhyt_nonpickup_cases c
  where c.dispense_date >= v_start and c.dispense_date < v_end;
end;
$$;

create or replace function public.bhyt_import_nonpickup_cases(p_cases jsonb)
returns integer language plpgsql security invoker set search_path = public as $$
declare
  v_case jsonb;
  v_key text;
  v_count integer := 0;
begin
  if jsonb_typeof(p_cases) <> 'array' then raise exception 'p_cases must be a JSON array'; end if;
  for v_case in select value from jsonb_array_elements(p_cases)
  loop
    v_key := nullif(v_case->>'record_key', '');
    if v_key is null or nullif(btrim(v_case->>'patient_name'), '') is null then
      raise exception 'record_key and patient_name are required';
    end if;
    insert into public.bhyt_nonpickup_cases (
      record_key, dispense_date, serial_no, visit_code, prescription_no,
      insurance_code, patient_name, phone, diagnosis, reason, reason_group, source_file
    ) values (
      v_key, (v_case->>'dispense_date')::date, nullif(v_case->>'serial_no', ''),
      nullif(v_case->>'visit_code', ''), nullif(v_case->>'prescription_no', ''),
      nullif(v_case->>'insurance_code', ''), v_case->>'patient_name', nullif(v_case->>'phone', ''),
      nullif(v_case->>'diagnosis', ''), v_case->>'reason', v_case->>'reason_group', nullif(v_case->>'source_file', '')
    )
    on conflict (record_key) do update set
      dispense_date = excluded.dispense_date, serial_no = excluded.serial_no,
      visit_code = excluded.visit_code, prescription_no = excluded.prescription_no,
      insurance_code = excluded.insurance_code, patient_name = excluded.patient_name,
      phone = excluded.phone, diagnosis = excluded.diagnosis, reason = excluded.reason,
      reason_group = excluded.reason_group, source_file = excluded.source_file;

    delete from public.bhyt_nonpickup_items where case_record_key = v_key;
    insert into public.bhyt_nonpickup_items (
      case_record_key, line_no, drug_code, drug_name, unit, quantity, unit_price,
      total_amount, insurance_amount, patient_amount
    )
    select v_key,
           entry.ordinality::integer,
           nullif(upper(btrim(entry.item->>'drug_code')), ''),
           entry.item->>'drug_name',
           coalesce(nullif(entry.item->>'unit', ''), 'viên'),
           coalesce(nullif(entry.item->>'quantity', '')::numeric, 0),
           coalesce(nullif(entry.item->>'unit_price', '')::numeric, 0),
           coalesce(
             nullif(entry.item->>'total_amount', '')::numeric,
             round(coalesce(nullif(entry.item->>'quantity', '')::numeric, 0)
               * coalesce(nullif(entry.item->>'unit_price', '')::numeric, 0), 2)
           ),
           coalesce(nullif(entry.item->>'insurance_amount', '')::numeric, 0),
           coalesce(nullif(entry.item->>'patient_amount', '')::numeric, 0)
    from jsonb_array_elements(coalesce(v_case->'items', '[]'::jsonb))
      with ordinality as entry(item, ordinality)
    where nullif(entry.item->>'drug_name', '') is not null;
    perform public.bhyt_refresh_case_totals(v_key);
    v_count := v_count + 1;
  end loop;
  return v_count;
end;
$$;

create or replace function public.bhyt_upsert_monthly_inventory(p_month date, p_rows jsonb)
returns integer language plpgsql security invoker set search_path = public as $$
declare
  v_row jsonb;
  v_count integer := 0;
  v_month date := date_trunc('month', p_month)::date;
begin
  if jsonb_typeof(p_rows) <> 'array' then raise exception 'p_rows must be a JSON array'; end if;
  for v_row in select value from jsonb_array_elements(p_rows)
  loop
    if nullif(btrim(v_row->>'drug_code'), '') is null or nullif(btrim(v_row->>'drug_name'), '') is null then
      raise exception 'drug_code and drug_name are required';
    end if;
    insert into public.bhyt_monthly_inventory (
      inventory_month, drug_code, drug_name, unit, opening_quantity, received_quantity,
      actual_issued_quantity, book_closing_quantity, physical_closing_quantity, nonpickup_in_issued
    ) values (
      v_month, upper(btrim(v_row->>'drug_code')), v_row->>'drug_name', coalesce(nullif(v_row->>'unit', ''), 'viên'),
      coalesce(nullif(v_row->>'opening_quantity', '')::numeric, 0),
      coalesce(nullif(v_row->>'received_quantity', '')::numeric, 0),
      coalesce(nullif(v_row->>'actual_issued_quantity', '')::numeric, 0),
      coalesce(nullif(v_row->>'book_closing_quantity', '')::numeric, 0),
      nullif(v_row->>'physical_closing_quantity', '')::numeric,
      coalesce(nullif(v_row->>'nonpickup_in_issued', '')::boolean, true)
    )
    on conflict (inventory_month, drug_code) do update set
      drug_name = excluded.drug_name, unit = excluded.unit,
      opening_quantity = excluded.opening_quantity, received_quantity = excluded.received_quantity,
      actual_issued_quantity = excluded.actual_issued_quantity,
      book_closing_quantity = excluded.book_closing_quantity,
      physical_closing_quantity = excluded.physical_closing_quantity,
      nonpickup_in_issued = excluded.nonpickup_in_issued;
    v_count := v_count + 1;
  end loop;
  return v_count;
end;
$$;

alter table public.bhyt_nonpickup_cases enable row level security;
alter table public.bhyt_nonpickup_items enable row level security;
alter table public.bhyt_monthly_inventory enable row level security;

drop policy if exists bhyt_cases_authenticated_all on public.bhyt_nonpickup_cases;
create policy bhyt_cases_authenticated_all on public.bhyt_nonpickup_cases
  for all to authenticated using (true) with check (true);
drop policy if exists bhyt_items_authenticated_all on public.bhyt_nonpickup_items;
create policy bhyt_items_authenticated_all on public.bhyt_nonpickup_items
  for all to authenticated using (true) with check (true);
drop policy if exists bhyt_inventory_authenticated_all on public.bhyt_monthly_inventory;
create policy bhyt_inventory_authenticated_all on public.bhyt_monthly_inventory
  for all to authenticated using (true) with check (true);

drop policy if exists "bhyt_nonpickup_authenticated_read" on public.bhyt_nonpickup_cases;
drop policy if exists "bhyt_nonpickup_authenticated_insert" on public.bhyt_nonpickup_cases;
drop policy if exists "bhyt_nonpickup_authenticated_update" on public.bhyt_nonpickup_cases;
drop policy if exists "bhyt_nonpickup_authenticated_delete" on public.bhyt_nonpickup_cases;

revoke all on function public.bhyt_get_dashboard(date, date) from public;
revoke all on function public.bhyt_import_nonpickup_cases(jsonb) from public;
revoke all on function public.bhyt_upsert_monthly_inventory(date, jsonb) from public;
grant execute on function public.bhyt_get_dashboard(date, date) to authenticated;
grant execute on function public.bhyt_import_nonpickup_cases(jsonb) to authenticated;
grant execute on function public.bhyt_upsert_monthly_inventory(date, jsonb) to authenticated;
grant select, insert, update, delete on public.bhyt_nonpickup_cases to authenticated;
grant select, insert, update, delete on public.bhyt_nonpickup_items to authenticated;
grant select, insert, update, delete on public.bhyt_monthly_inventory to authenticated;
grant usage, select on sequence public.bhyt_nonpickup_items_id_seq to authenticated;
grant usage, select on sequence public.bhyt_monthly_inventory_id_seq to authenticated;
grant select on public.bhyt_daily_nonpickup_summary to authenticated;
grant select on public.bhyt_monthly_nonpickup_summary to authenticated;
grant select on public.bhyt_monthly_inventory_reconciliation to authenticated;
